import { DashHeader } from "@/components/dashboard/header";
import { OpenClawBadge } from "@/components/ui/openclaw-badge";
import { OpenClawMetricsBar } from "@/components/ui/openclaw-metrics-bar";
import { StatusBadge } from "@/components/ui/status-badge";
import { MOCK_PROJECTS, MOCK_RENDER_JOBS } from "@/lib/mock-data";
import { OPENCLAW_SUMMARY } from "@/lib/openclaw";
import { FolderOpen, Film, Cpu, Users, ArrowRight, Zap, Clock } from "lucide-react";
import Link from "next/link";

const stats = [
  { label: "Projects", value: "6", icon: FolderOpen, sub: "+2 this month", color: "text-indigo-400 bg-indigo-500/10" },
  { label: "Renders", value: "1,247", icon: Film, sub: "48 queued", color: "text-pink-400 bg-pink-500/10" },
  { label: "Episodes", value: "63", icon: Cpu, sub: "12 in pipeline", color: "text-violet-400 bg-violet-500/10" },
  { label: "Characters", value: "24", icon: Users, sub: "8 DNA-locked", color: "text-cyan-400 bg-cyan-500/10" },
];

const activity = [
  { text: "OpenClaw rendered 31/48 scenes for", target: "Neon Ronin EP 3", time: "3m ago" },
  { text: "Script Writer completed draft for", target: "Void Whisperers EP 2", time: "18m ago" },
  { text: "Yuki Ren DNA profile updated", target: "Character DNA Vault", time: "1h ago" },
  { text: "Trend Radar alert:", target: "Isekai content up 840% on TikTok", time: "2h ago" },
  { text: "Sakura Requiem track generated by", target: "Music Composer", time: "4h ago" },
];

export default function DashboardPage() {
  const renderHoursUsed = 87;
  const storageUsed = 42;

  return (
    <div>
      <DashHeader title="Dashboard" description="Your production studio overview" />
      <div className="p-5 space-y-5">
        {/* OpenClaw Engine Status */}
        <div className="glass rounded-2xl p-4 border border-indigo-500/20 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-600/10 to-transparent pointer-events-none" />
          <div className="relative flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-indigo-500/20 rounded-xl flex items-center justify-center">
                <Cpu className="w-5 h-5 text-indigo-400" />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-0.5">
                  <p className="font-semibold text-white text-sm">OpenClaw Engine</p>
                  <OpenClawBadge label="Active" />
                </div>
                <OpenClawMetricsBar metrics={[
                  { label: "Active agents", value: OPENCLAW_SUMMARY.activeAgents },
                  { label: "Tasks running", value: OPENCLAW_SUMMARY.totalTasksRunning },
                  { label: "Accuracy", value: OPENCLAW_SUMMARY.avgAccuracy, unit: "%" },
                  { label: "Uptime", value: OPENCLAW_SUMMARY.avgUptime, unit: "%", color: "text-emerald-400" },
                ]} />
              </div>
            </div>
            <Link href="/episode-pipeline" className="flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 transition-colors">
              View pipeline <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>

        {/* Stat cards */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((s) => (
            <div key={s.label} className="glass rounded-2xl p-4">
              <div className={`w-9 h-9 ${s.color} rounded-xl flex items-center justify-center mb-3`}>
                <s.icon className="w-4.5 h-4.5" />
              </div>
              <div className="text-2xl font-bold text-white">{s.value}</div>
              <div className="text-xs text-gray-500 mt-0.5">{s.label}</div>
              <div className="text-xs text-indigo-400 mt-1">{s.sub}</div>
            </div>
          ))}
        </div>

        {/* Usage meters */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            { label: "Render Hours", used: renderHoursUsed, limit: 100, unit: "hrs", color: "bg-indigo-500" },
            { label: "Storage", used: storageUsed, limit: 100, unit: "GB", color: "bg-pink-500" },
          ].map((m) => (
            <div key={m.label} className="glass rounded-2xl p-4">
              <div className="flex items-center justify-between text-xs mb-2">
                <span className="text-gray-400">{m.label}</span>
                <span className="text-gray-300">{m.used} / {m.limit} {m.unit}</span>
              </div>
              <div className="h-2 bg-white/8 rounded-full overflow-hidden">
                <div className={`h-full ${m.color} rounded-full`} style={{ width: `${m.used}%` }} />
              </div>
              <p className="text-xs text-gray-600 mt-1">{m.used}% used — resets in 8 days</p>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          {/* Recent Projects */}
          <div className="lg:col-span-2 glass rounded-2xl overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3.5 border-b border-white/8">
              <h2 className="text-sm font-semibold text-white">Recent Projects</h2>
              <Link href="/projects" className="text-xs text-indigo-400 hover:text-indigo-300 flex items-center gap-1">All projects <ArrowRight className="w-3 h-3" /></Link>
            </div>
            <div className="divide-y divide-white/5">
              {MOCK_PROJECTS.slice(0, 4).map((p) => (
                <div key={p.id} className="flex items-center justify-between px-5 py-3 hover:bg-white/[0.03] transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-gradient-to-br from-indigo-500/30 to-pink-500/30 rounded-lg flex items-center justify-center">
                      <Film className="w-4 h-4 text-indigo-400" />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-white">{p.title}</p>
                      <p className="text-xs text-gray-600">{p.genre} · {p.episodeCount} episodes</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    {p.openclawEnabled && <OpenClawBadge size="sm" label="AI" />}
                    <StatusBadge status={p.status} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Active Renders + Activity */}
          <div className="space-y-4">
            {/* Active renders */}
            <div className="glass rounded-2xl overflow-hidden">
              <div className="flex items-center justify-between px-4 py-3 border-b border-white/8">
                <h2 className="text-sm font-semibold text-white">Active Renders</h2>
                <Link href="/render-queue" className="text-xs text-indigo-400">View all</Link>
              </div>
              <div className="divide-y divide-white/5">
                {MOCK_RENDER_JOBS.filter(r => r.status === "Rendering").map((r) => (
                  <div key={r.id} className="px-4 py-3">
                    <p className="text-xs font-medium text-white mb-1 truncate">{r.episode}</p>
                    <div className="flex items-center justify-between text-xs text-gray-500 mb-1.5">
                      <span>{r.resolution} · {r.gpu}</span>
                      <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{r.eta}</span>
                    </div>
                    <div className="h-1.5 bg-white/8 rounded-full overflow-hidden">
                      <div className="h-full bg-indigo-500 rounded-full animate-pulse-slow" style={{ width: `${r.progress}%` }} />
                    </div>
                    <p className="text-xs text-gray-600 mt-1">{r.progress}% complete</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Quick Actions */}
            <div className="glass rounded-2xl p-4">
              <h2 className="text-sm font-semibold text-white mb-3">Quick Actions</h2>
              <div className="space-y-1.5">
                {[
                  { label: "New Project", href: "/projects", icon: FolderOpen },
                  { label: "Open Pipeline", href: "/episode-pipeline", icon: Zap },
                  { label: "Render Queue", href: "/render-queue", icon: Cpu },
                ].map((a) => (
                  <Link key={a.label} href={a.href}
                    className="flex items-center gap-2 p-2 rounded-xl hover:bg-white/5 transition-colors text-xs text-gray-400 hover:text-white group">
                    <a.icon className="w-4 h-4 group-hover:text-indigo-400 transition-colors" />
                    {a.label}
                    <ArrowRight className="w-3 h-3 ml-auto opacity-0 group-hover:opacity-100 transition-opacity" />
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Activity Feed */}
        <div className="glass rounded-2xl p-5">
          <h2 className="text-sm font-semibold text-white mb-4">Activity Feed</h2>
          <div className="space-y-3">
            {activity.map((item, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0" />
                <p className="text-xs text-gray-400 flex-1">
                  {item.text} <span className="text-indigo-300 font-medium">{item.target}</span>
                </p>
                <span className="text-xs text-gray-600 shrink-0">{item.time}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
